platform :ios, '5.0'

link_with 'SpatialDBKitiOS', 'SpatialDBKitiOSTests'

pod 'SpatialDBKit', :path => '../../'

pre_install do |installer_representation|
    path = Pathname(installer_representation.sandbox.pod_dir("spatialite"))+"src/spatialite/spatialite.c"

    text = File.read(path)
  	new_text = text.gsub(/#include <spatialite\/spatialite\.h>/, "#include <spatialite/spatialite/spatialite.h>")

  	File.open(path, "w") {|file| file.puts new_text }

end